import os

USERNAME = os.getlogin()
APP_WIDTH = 500
APP_HEIGHT = 300
BUTTON_WIDTH = 170
BUTTON_HEIGHT = 30
TIMER_BLOCK_Y_CORDS = 70
NOTIFICATION_BLOCK_Y_CORDS = 150
NOTIFICATION_TIMER_Y_CORDS = 200
BLOCK_MARGIN = 10
